language: php

php:
  - 7.0

env:
  - SYMFONY_VERSION=2.7.*

before_script:
  - composer self-update
  - composer require symfony/framework-bundle:${SYMFONY_VERSION} --no-update
  - composer update --no-interaction --prefer-source
  - ./src/BeSimple/SoapClient/Tests/bin/phpwebserver.sh
  - ./src/BeSimple/SoapClient/Tests/bin/axis.sh

script:
  - phpunit --coverage-text
